version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./static:/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-server
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - minio
    ports:
      - "8080:8080"

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
